### ISSUE TITLE
pip package issue

### ISSUE THREAD

**Issue by b3nw** [kevinsteves/pan-python#9]
$ pip install pan
Collecting pan
  Using cached pan-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/47/ysvfpggx7fj4wjd3ncvstjdwhzv7dt/T/pip-build-vY9ibG/pan/setup.py", line 1, in <module>
        import distribute_setup
    ImportError: No module named distribute_setup

**Comment by kevinsteves** [comment]
the package name is pan-python

**Comment by b3nw** [comment]
derp... that would do it. Thanks
